name: Build and Deployment

on:
  push:
    branches:
      - 'source'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: NPM install
      run: npm install
      
    - name: NPM Build & Deploy
      run: npm run deploy
