name: Build and Deployment

on:
  push:
    branches:
      - 'source'

jobs:
  Build and Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: NPM install
      run: npm install
      
    - name: Configure GIT
      run: |
        git config --global user.email "jamie.haywood@gmail.com"
        git config --global user.name "jamiehaywood"
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/jamiehaywood/jamiehaywood.github.io.git
    
    - name: NPM Build & Deploy
      run: npm run deploy